
name: climate-modeling-env
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11.11
  - numpy=2.0.2
  - pandas=2.2.2
  - matplotlib=3.10.0
  - xarray=2025.1.2
  - scipy=1.14.1
  - jupyterlab
  - pip
  - pip:
      - scikit-learn==1.6.1
      - tensorflow==2.18.0
      - keras==3.8.0
      - netCDF4==1.7.2
      - cftime==1.6.4.post1
      - h5netcdf==1.6.1
      - seaborn==0.13.2
